### ISSUE TITLE
Add categories support

### ISSUE THREAD

**Issue by TokyFy** [lovincyrus/coolection#1]
Add a folder-like component to organize links into categories.

Eg. 
Music
  - link
  - link
work
  - link
  - link

**Comment by lovincyrus** [comment]
Great suggestion! It's already on the roadmap. Adding categories/lists, tags, and note fields is part of the considerations at the moment.

PS: there's already a folder-like functionality, called list in the [schema prisma](https://github.com/lovincyrus/coolection/blob/main/prisma/schema.prisma). Still need some work with list creation and wiring up the lists on the UI.

**Comment by lovincyrus** [comment]
Adding items to a list is now available! 🙌🏼 

https://github.com/lovincyrus/coolection/assets/1021101/48608782-f999-44c9-a992-fec1c6bf2219
