### ISSUE TITLE
Only domain saved instead of Full Url

### ISSUE THREAD

**Issue by TokyFy** [lovincyrus/coolection#3]
I tried to save a YouTube link like "https://www.youtube.com/watch?v=C6CeA6vRtW4&list=TLPQMjcwNTIwMjR4C9UT27Pxag&index=11" but it said it's already added.

I noticed that only "[www.youtube.com](http://www.youtube.com/)" was added, and the metadata (the music title, in this case) isn't shown.

**Comment by lovincyrus** [comment]
Fixed in https://github.com/lovincyrus/coolection/commit/bd91ec36fdc3462bd9348eac0ee08d9251778c64

![CleanShot 2024-05-27 at 22 05 12@2x](https://github.com/lovincyrus/coolection/assets/1021101/088bd5be-6ee4-4cab-95a0-c95d13f8d43a)
